version: 2

jobs:
  checkout:
    docker:
      - image: cimg/base:stable
    resource_class: small
    steps:
      - checkout
      - persist_to_workspace:
          root: ~/
          paths:
            - project
  build_laravel9:
    docker:
      - image: cimg/base:stable
    resource_class: small
    steps:
      - attach_workspace:
          at: ~/
      - setup_remote_docker:
          version: 20.10.7
          docker_layer_caching: true
      - run:
          name: Building laravel image
          command: docker-compose build laravel9
      - run:
          name: Saving image
          command: docker save -o ~/laravel9 project_laravel9
      - persist_to_workspace:
          root: ~/
          paths:
            - laravel9
  publish_laravel9:
    docker:
      - image: cimg/base:stable
    resource_class: small
    steps:
      - attach_workspace:
          at: ~/
      - setup_remote_docker:
          version: 20.10.7
          docker_layer_caching: true
      - run:
          name: Loading image
          command: docker load -i ~/laravel9
      - run:
          name: Logging into dockerhub
          command: docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD}
      - run:
          name: Publishing image
          command: |
            docker tag project_laravel9 ${DOCKER_USERNAME}/laravel:9
            docker tag project_laravel9 ${DOCKER_USERNAME}/laravel:latest
            docker push ${DOCKER_USERNAME}/laravel:9
            docker push ${DOCKER_USERNAME}/laravel:latest
      - run:
          name: Remove dangling images
          command: docker image prune -a -f

workflows:
  version: 2
  build-and-publish:
    jobs:
      - checkout
      - build_laravel9:
          requires:
            - checkout
      - publish_laravel9:
          requires:
            - build_laravel9
          filters:
            branches:
              only:
                - main
